#!/usr/bin/env python3
"""NFC tables for ds4's tokenizer, from Python's unicodedata.

The Qwen3.8 tokenizer.json normalizes its input to NFC before the pre-tokenizer
regex, so a decomposed "e" + U+0301 must tokenize as the precomposed U+00E9.
Three tables carry the algorithm (UAX #15): full canonical decompositions of
every character that has one (Hangul syllables are algorithmic and omitted),
non-zero canonical combining classes, and the primary composites as
(first, second) -> composed pairs, exclusions already removed.

  python3 gguf-tools/qwen4exp_nfc_tables.py > ds4_unicode_nfc.inc
"""
import sys
import unicodedata as ud


def full_decomp(cp):
    out = []
    stack = [cp]
    while stack:
        c = stack.pop()
        d = ud.decomposition(chr(c))
        if not d or d.startswith('<') or 0xAC00 <= c <= 0xD7A3:
            out.append(c)
            continue
        parts = [int(x, 16) for x in d.split()]
        stack.extend(reversed(parts))
    return out


def main():
    w = sys.stdout.write
    decomp = []      # (cp, [parts])
    ccc = []         # (cp, class)
    comp = {}        # (first, second) -> composed
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        ch = chr(cp)
        c = ud.combining(ch)
        if c:
            ccc.append((cp, c))
        d = ud.decomposition(ch)
        if d and not d.startswith('<') and not (0xAC00 <= cp <= 0xD7A3):
            parts = full_decomp(cp)
            decomp.append((cp, parts))
            raw = [int(x, 16) for x in d.split()]
            # primary composite: a two-character canonical decomposition that
            # NFC recomposes (not in the exclusion list, not a singleton)
            if len(raw) == 2 and ud.normalize('NFC', ''.join(map(chr, raw))) == ch:
                comp[(raw[0], raw[1])] = cp
    maxlen = max(len(p) for _, p in decomp)
    w("/* Generated by gguf-tools/qwen4exp_nfc_tables.py (Unicode %s via Python\n" % ud.unidata_version)
    w(" * unicodedata): canonical decompositions, combining classes and primary\n")
    w(" * composites for NFC.  Do not edit; regenerate. */\n\n")
    w("#define NFC_DECOMP_MAX %d\n" % maxlen)
    w("typedef struct { uint32_t cp; uint8_t n; uint32_t seq[%d]; } nfc_decomp;\n" % maxlen)
    w("typedef struct { uint32_t cp; uint8_t ccc; } nfc_ccc;\n")
    w("typedef struct { uint32_t first, second, composed; } nfc_pair;\n\n")
    w("static const nfc_decomp nfc_decomps[%d] = {\n" % len(decomp))
    for cp, parts in decomp:
        w("    {0x%05x, %d, {%s}},\n" % (cp, len(parts), ", ".join("0x%05x" % p for p in parts)))
    w("};\n\n")
    # ccc as ranges of equal class
    ranges = []
    for cp, c in ccc:
        if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == c:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, c])
    w("typedef struct { uint32_t lo, hi; uint8_t ccc; } nfc_ccc_range;\n")
    w("static const nfc_ccc_range nfc_cccs[%d] = {\n" % len(ranges))
    for i in range(0, len(ranges), 4):
        w("    " + " ".join("{0x%05x, 0x%05x, %d}," % tuple(r) for r in ranges[i:i + 4]) + "\n")
    w("};\n\n")
    pairs = sorted(comp.items())
    w("static const nfc_pair nfc_pairs[%d] = {\n" % len(pairs))
    for i in range(0, len(pairs), 3):
        w("    " + " ".join("{0x%05x, 0x%05x, 0x%05x}," % (a, b, c) for (a, b), c in pairs[i:i + 3]) + "\n")
    w("};\n")


if __name__ == "__main__":
    main()
